name: Build workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Build
        run: go build
      - name: Test
        run: go test -cover > unit-test-results.txt && cat unit-test-results.txt
      - name: Upload unit test results
        uses: actions/upload-artifact@v1
        with:
          name: unit-test-results
          path: unit-test-results.txt